/**
 * Texto corrido das Políticas da Woody, exibido para leitura e confirmação no onboarding.
 * Conteúdo reproduzido sem alterações a partir dos documentos oficiais
 * "Políticas de Segurança, Privacidade e Comunidade" e "Política de Cookies e Tecnologias Locais".
 * Itens iniciados por "•" correspondem a listas dos documentos originais.
 */
export interface PolicyContentSection {
  heading: string;
  paragraphs: string[];
}

export const WOODY_POLICIES_UPDATED_AT = "Última atualização: 06 de junho de 2026";

export const WOODY_POLICIES_SECTIONS: PolicyContentSection[] = [
  {
    heading: "1. Termos de Uso da WOODY",
    paragraphs: [
      "Estes Termos de Uso regulam o acesso e a utilização da plataforma digital WOODY, mantida por WOODY PLATAFORMA DIGITAL LTDA., pessoa jurídica de direito privado, inscrita no CNPJ sob nº [inserir], com sede em [inserir], doravante denominada WOODY.",
      "Ao criar uma conta, acessar ou utilizar a plataforma, a usuária declara que leu, compreendeu e concorda com estes Termos, com a Política de Privacidade, com as Diretrizes da Comunidade, com a Política de Segurança e, quando aplicável, com a Política de Cookies.",
      "1.1 Natureza da plataforma",
      "A WOODY é uma plataforma digital privada, orientada por comunidades, criada para promover conexões, conversas, publicações, interações sociais e trocas entre mulheres LBP e pessoas sáficas alinhadas ao feminino, conforme a proposta pública, as regras de acesso e os critérios de segurança da plataforma.",
      "A WOODY não é serviço de emergência, serviço terapêutico, serviço de investigação, agência de encontros, garantidora de compatibilidade entre usuárias ou certificadora absoluta de identidade, antecedentes, intenção ou comportamento.",
      "1.2 Elegibilidade e idade mínima",
      "• O uso da plataforma é permitido apenas a pessoas maiores de 18 anos.",
      "• Não é permitido criar conta, acessar funcionalidades ou fornecer dados pessoais em nome de pessoa menor de idade.",
      "• A WOODY poderá solicitar informações adicionais ou documento oficial quando houver dúvida razoável sobre idade, autenticidade, segurança da comunidade, fraude ou cumprimento legal.",
      "• Contas suspeitas, incompatíveis com a proposta da plataforma ou que representem risco poderão ser limitadas, suspensas ou removidas, respeitados os critérios internos e a legislação aplicável.",
      "1.3 Cadastro, conta e responsabilidade da usuária",
      "• A usuária deve fornecer informações verdadeiras, completas e atualizadas.",
      "• A conta é pessoal e intransferível. Não é permitido vender, emprestar, compartilhar ou permitir o uso da conta por terceiros.",
      "• A usuária é responsável por manter a confidencialidade de sua senha, dispositivo, e-mail de acesso e demais credenciais.",
      "• A WOODY poderá impedir nomes, imagens, descrições ou identificadores que violem direitos de terceiros, induzam erro, simulem vínculo com a plataforma ou comprometam a segurança da comunidade.",
      "1.4 Funcionalidades",
      "A plataforma poderá disponibilizar, entre outras funcionalidades, criação de perfil, publicações, comentários, reações, mensagens privadas, comunidades públicas ou privadas, busca, recomendações, denúncias, recursos de moderação, planos pagos e ferramentas de interação social.",
      "As funcionalidades podem ser alteradas, ajustadas, descontinuadas ou substituídas, especialmente durante fases de teste, evolução técnica, lançamento gradual, manutenção, segurança ou adequação legal.",
      "1.5 Conteúdos gerados por usuárias",
      "• A usuária é responsável pelos conteúdos que publica, envia, comenta, reage, transmite ou compartilha.",
      "• A WOODY atua como ambiente de hospedagem e interação, sem controle prévio obrigatório de tudo o que é publicado.",
      "• Conteúdos publicados em áreas compartilhadas podem ser acessados por outras usuárias conforme a configuração da funcionalidade, da comunidade e da conta.",
      "• É proibido publicar conteúdo ilegal, fraudulento, discriminatório, violento, assediador, ameaçador, abusivo, sexualmente exploratório, invasivo da privacidade alheia ou que viole direitos de terceiros.",
      "1.6 Comunidades",
      "A WOODY poderá permitir a criação, administração e participação em comunidades. Comunidades podem ter regras próprias, desde que não contrariem estes Termos, as Diretrizes da Comunidade, a legislação aplicável e a proposta geral da plataforma.",
      "• Administradoras de comunidades devem aplicar regras de forma proporcional, consistente e respeitosa.",
      "• A WOODY poderá intervir em comunidades que apresentem risco à segurança, violação de direitos, fraude, abuso, assédio, discriminação, exposição indevida de dados ou descumprimento das políticas da plataforma.",
      "• Comunidades privadas não devem ser utilizadas para burlar regras, esconder práticas ilícitas ou promover exclusão ofensiva, perseguição ou dano a terceiros.",
      "1.7 Planos pagos, pagamentos e cobranças",
      "A WOODY poderá oferecer planos gratuitos e pagos. As condições comerciais, funcionalidades incluídas, valores, periodicidade, renovação, cancelamento e eventuais benefícios serão informados nos fluxos de contratação e nas páginas correspondentes da plataforma.",
      "• Pagamentos poderão ser processados por provedores terceiros, como instituições de pagamento, gateways, antifraude e ferramentas de cobrança.",
      "• A WOODY não armazena, em seus próprios servidores, os dados completos de cartão de crédito ou débito.",
      "• A ativação, renovação, suspensão ou cancelamento de benefícios pagos poderá depender da confirmação do provedor de pagamento.",
      "• Falhas de pagamento, suspeita de fraude, chargeback, cancelamento ou descumprimento dos Termos poderão resultar em limitação ou interrupção de funcionalidades pagas.",
      "1.8 Moderação, denúncias e medidas de segurança",
      "A WOODY poderá realizar moderação manual e/ou automatizada para proteger a plataforma, as usuárias e a integridade da comunidade. A moderação pode envolver análise de conteúdo, comportamento, denúncias, padrões de uso, sinais de fraude e registros técnicos.",
      "• As medidas podem incluir aviso, remoção de conteúdo, limitação de alcance, restrição de funcionalidade, suspensão temporária, exclusão de conta, bloqueio de acesso e preservação de registros.",
      "• Em situações de risco, fraude, ameaça, assédio grave, exposição de dados, violência, ilegalidade ou tentativa de burlar controles, a WOODY poderá agir preventivamente.",
      "• A WOODY poderá cooperar com autoridades competentes mediante requisição legal válida.",
      "1.9 Limitação de responsabilidade",
      "Na máxima extensão permitida pela legislação aplicável, a WOODY não se responsabiliza por condutas, conteúdos, informações, promessas, interações, encontros, acordos ou relações estabelecidas entre usuárias dentro ou fora da plataforma, salvo quando houver responsabilidade legal própria comprovada.",
      "A WOODY não garante que a plataforma estará livre de falhas, interrupções, instabilidades, tentativas de acesso não autorizado ou indisponibilidades decorrentes de manutenção, provedores terceiros, eventos externos, ataques, caso fortuito ou força maior. A plataforma adotará medidas razoáveis para reduzir riscos e restabelecer os serviços quando possível.",
      "1.10 Alterações dos Termos",
      "A WOODY poderá atualizar estes Termos para refletir mudanças legais, técnicas, comerciais ou operacionais. Alterações relevantes poderão ser comunicadas por meios razoáveis, como aviso na plataforma, e-mail ou atualização da página correspondente. O uso continuado da plataforma após a vigência da nova versão indica ciência e aceitação das mudanças, quando legalmente aplicável.",
    ],
  },
  {
    heading: "2. Política de Privacidade",
    paragraphs: [
      "Esta Política de Privacidade explica como a WOODY coleta, usa, armazena, compartilha e protege dados pessoais no contexto da plataforma. Ela deve ser lida em conjunto com os Termos de Uso, a Política de Segurança, as Diretrizes da Comunidade e a Política de Cookies, quando aplicável.",
      "2.1 Definições essenciais",
      "Dados pessoais: informações relacionadas a pessoa natural identificada ou identificável, como nome, e-mail, foto, identificadores técnicos e dados de conta.",
      "Dados pessoais sensíveis: dados sobre origem racial ou étnica, convicção religiosa, opinião política, filiação sindical, saúde, vida sexual, dado genético ou biométrico, nos termos da LGPD.",
      "Tratamento: toda operação com dados pessoais, como coleta, uso, acesso, armazenamento, compartilhamento, eliminação ou anonimização.",
      "Controladora: a pessoa jurídica que decide como e por que os dados pessoais são tratados. Neste documento, a WOODY.",
      "Operadora: pessoa física ou jurídica que trata dados pessoais em nome da controladora, conforme instruções recebidas.",
      "Titular: pessoa natural a quem os dados pessoais se referem. Neste documento, a usuária.",
      "Encarregado: pessoa ou função indicada para atuar como canal de comunicação sobre proteção de dados, quando aplicável.",
      "2.2 Quais dados podem ser tratados",
      "a) Dados fornecidos pela usuária",
      "• Dados de cadastro: nome, e-mail, data de nascimento, senha ou credenciais, foto de perfil, nome de usuária e demais informações informadas voluntariamente.",
      "• Dados de perfil: bio, imagens, preferências, interesses, comunidades, publicações, comentários, reações e outras informações exibidas conforme a dinâmica da plataforma.",
      "• Dados de suporte e comunicação: mensagens enviadas ao suporte, formulários, pesquisas, solicitações, denúncias, comunicações com a WOODY e interações com e-mails enviados pela plataforma.",
      "• Dados de verificação: documento oficial, foto, data de nascimento, número de documento e, quando necessário e juridicamente adequado, elementos biométricos ou validações por terceiros.",
      "b) Dados de conteúdo e interação",
      "• Publicações, comentários, respostas, curtidas, reações, comunidades, denúncias, mensagens, mídias e demais interações realizadas na plataforma.",
      "• Metadados associados às interações, como data, hora, remetente, destinatária, comunidade, status de envio, registro de edição ou remoção.",
      "c) Dados coletados automaticamente",
      "• Endereço IP, tipo de dispositivo, sistema operacional, navegador, identificadores técnicos, registros de acesso, logs de segurança e dados de uso.",
      "• Páginas acessadas, funcionalidades utilizadas, tempo de permanência, cliques, fluxo de navegação, preferências e histórico de interação dentro da plataforma.",
      "• Localização aproximada derivada do IP e, se houver funcionalidade específica, localização mais precisa apenas mediante consentimento ou outra base legal aplicável.",
      "d) Dados de pagamento",
      "• Identificador da transação, plano contratado, data, valor, status de pagamento, forma de pagamento, histórico de cobranças, cancelamentos e reembolsos.",
      "• Dados de faturamento necessários para cobrança, prevenção a fraude e cumprimento de obrigações legais ou fiscais.",
      "• Dados completos de cartão são tratados pelo provedor de pagamento contratado, e não armazenados integralmente pela WOODY em seus servidores.",
      "2.3 Dados potencialmente sensíveis",
      "Pela natureza da plataforma, algumas informações fornecidas voluntariamente pela usuária podem revelar ou sugerir aspectos de vida sexual, orientação afetiva, preferências pessoais, pertencimento comunitário ou outros elementos sensíveis. A WOODY deve tratar esses dados com cuidado reforçado, limitação de acesso, finalidade definida e base legal adequada.",
      "Atenção especial: quando o tratamento envolver dado pessoal sensível, a base legal deve ser avaliada com rigor. O consentimento pode ser necessário em algumas situações, mas nem sempre será a única base possível. Essa definição precisa refletir o fluxo real do produto e deve ser validada juridicamente antes da publicação.",
      "2.4 Para que os dados são usados",
      "• Criar, autenticar e proteger contas.",
      "• Operar perfis, publicações, comunidades, mensagens, comentários, reações, busca e recomendações.",
      "• Viabilizar conexões sociais e funcionalidades de relacionamento interpessoal.",
      "• Personalizar a experiência conforme preferências, interesses e histórico de interação.",
      "• Processar pagamentos, assinaturas, cancelamentos, reembolsos e suporte financeiro.",
      "• Prevenir fraude, abuso, assédio, spam, violação de regras, uso indevido, contas falsas e riscos à segurança.",
      "• Analisar denúncias, moderar conteúdos e aplicar medidas previstas nas políticas da plataforma.",
      "• Melhorar desempenho, estabilidade, acessibilidade, usabilidade e qualidade dos serviços.",
      "• Cumprir obrigações legais, regulatórias, fiscais, contratuais e ordens de autoridades competentes.",
      "• Exercer direitos em processos judiciais, administrativos ou arbitrais.",
      "2.5 Bases legais",
      "O tratamento de dados pessoais poderá se apoiar, conforme o caso, nas seguintes bases legais previstas na LGPD:",
      "• Execução de contrato ou procedimentos preliminares relacionados ao uso da plataforma.",
      "• Cumprimento de obrigação legal ou regulatória.",
      "• Exercício regular de direitos.",
      "• Legítimo interesse, especialmente para segurança, prevenção a fraudes, melhoria dos serviços e proteção da comunidade, sempre com avaliação de necessidade, proporcionalidade e expectativa da titular.",
      "• Consentimento, quando exigido ou adequado, especialmente para determinadas operações com dados sensíveis, comunicações opcionais, geolocalização precisa ou tecnologias não essenciais.",
      "• Proteção da vida ou da incolumidade física, em situações excepcionais previstas em lei.",
      "2.6 Compartilhamento de dados",
      "A WOODY poderá compartilhar dados pessoais apenas quando necessário, adequado e compatível com as finalidades descritas nesta Política, incluindo:",
      "• Com outras usuárias, quando a própria funcionalidade envolver exposição de perfil, publicação, comunidade, comentário, reação, mensagem ou interação.",
      "• Com provedores de infraestrutura, hospedagem, armazenamento, autenticação, envio de e-mails, suporte, segurança, moderação, análise de desempenho e processamento de pagamentos.",
      "• Com instituições financeiras, ferramentas antifraude e processadores de pagamento, quando necessário para cobrança e prevenção de fraude.",
      "• Com autoridades públicas, mediante obrigação legal, ordem válida ou cooperação exigida pela legislação aplicável.",
      "• Em operações societárias, como fusão, aquisição, reorganização, venda de ativos ou captação, resguardadas medidas adequadas de confidencialidade e proteção de dados.",
      "2.7 Transferência internacional",
      "Alguns provedores tecnológicos utilizados pela WOODY podem tratar ou armazenar dados fora do Brasil. Quando houver transferência internacional de dados pessoais, a WOODY deverá observar as exigências da LGPD e adotar mecanismos adequados de proteção, conforme aplicável.",
      "2.8 Retenção e eliminação",
      "Os dados pessoais serão mantidos pelo tempo necessário ao cumprimento das finalidades descritas nesta Política, à execução dos serviços, ao cumprimento de obrigações legais ou regulatórias, à prevenção de fraudes e ao exercício regular de direitos. Encerrada a finalidade e inexistindo obrigação ou justificativa legal de retenção, os dados poderão ser eliminados ou anonimizados.",
      "• Dados de conta podem ser mantidos enquanto a conta estiver ativa.",
      "• Logs de segurança podem ser mantidos por período compatível com prevenção de fraude, investigação de incidentes e obrigações legais.",
      "• Registros de pagamento podem ser mantidos por prazos fiscais, contábeis e legais.",
      "• Denúncias e medidas de moderação podem ser preservadas para auditoria, segurança e prevenção de reincidência.",
      "2.9 Direitos da titular",
      "Nos termos da LGPD, a titular poderá solicitar, conforme aplicável:",
      "• Confirmação da existência de tratamento.",
      "• Acesso aos dados pessoais.",
      "• Correção de dados incompletos, inexatos ou desatualizados.",
      "• Anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade.",
      "• Portabilidade, observados os requisitos legais e regulamentares.",
      "• Informações sobre compartilhamento de dados.",
      "• Revogação do consentimento, quando o tratamento depender dessa base legal.",
      "• Informação sobre a possibilidade de não fornecer consentimento e sobre as consequências da negativa.",
      "• Oposição a tratamento realizado em desconformidade com a LGPD.",
      "• Revisão de decisões tomadas unicamente com base em tratamento automatizado, quando aplicável.",
      "As solicitações poderão ser feitas pelo canal: [inserir e-mail/canal de privacidade]. A WOODY poderá solicitar informações adicionais para confirmar a identidade da solicitante e proteger a conta contra acesso indevido.",
      "2.10 Cookies e tecnologias similares",
      "A WOODY poderá utilizar cookies, pixels, SDKs, scripts, web beacons e tecnologias similares para funcionamento da plataforma, segurança, autenticação, melhoria da experiência, análise de desempenho e, se aplicável, publicidade ou mensuração. As informações específicas sobre categorias, finalidades, terceiros e formas de gestão devem constar em Política de Cookies própria, disponibilizada em anexo separado e por link visível na plataforma.",
      "Política de Cookies: a Política de Cookies consta em documento separado e deve ser disponibilizada em link próprio nesta seção e no rodapé da plataforma. (O texto integral dessa política está reproduzido ao final deste documento.)",
      "2.11 Encarregado e contato",
      "• Canal de privacidade: [inserir e-mail].",
      "• Encarregado: [inserir nome, função ou canal, conforme decisão da empresa].",
      "• Endereço da controladora: [inserir].",
    ],
  },
  {
    heading: "3. Política de Segurança da Informação",
    paragraphs: [
      "A WOODY adota medidas técnicas, administrativas e organizacionais para proteger dados pessoais, contas, conteúdos e a integridade da plataforma. Nenhuma medida de segurança é absoluta, mas a plataforma deve trabalhar com prevenção, monitoramento, resposta e melhoria contínua.",
      "3.1 Medidas adotadas pela WOODY",
      "• Controle de acesso a sistemas internos conforme necessidade e função.",
      "• Uso de autenticação, criptografia em trânsito, registros de acesso e medidas de proteção contra acesso não autorizado.",
      "• Monitoramento de falhas, tentativas de abuso, comportamento suspeito, spam, fraude e uso indevido.",
      "• Práticas de desenvolvimento seguro, revisão de permissões e correção de vulnerabilidades identificadas.",
      "• Segregação de ambientes, proteção de credenciais e limitação de acesso a dados sensíveis.",
      "• Contratação de provedores que adotem padrões adequados de segurança, quando aplicável.",
      "• Procedimentos de resposta a incidentes, incluindo análise, contenção, mitigação, registro e comunicação quando exigida por lei.",
      "3.2 Deveres da usuária",
      "• Usar senha forte e não compartilhá-la com terceiros.",
      "• Manter e-mail, dispositivo, navegador e sistema operacional protegidos e atualizados.",
      "• Não emprestar, vender, transferir ou permitir o uso da conta por outra pessoa.",
      "• Sair da conta ao usar dispositivos compartilhados.",
      "• Não tentar acessar contas, comunidades, sistemas, dados ou áreas restritas sem autorização.",
      "• Reportar à WOODY suspeitas de invasão, golpe, perfil falso, vazamento, assédio, extorsão, engenharia social ou comportamento inseguro.",
      "3.3 Incidentes de segurança",
      "Caso identifique incidente de segurança que possa acarretar risco ou dano relevante às titulares, a WOODY deverá avaliar o ocorrido, adotar medidas de contenção e mitigação, documentar as providências e realizar comunicações exigidas pela legislação aplicável, inclusive à ANPD e às titulares, quando cabível.",
      "3.4 Limites técnicos",
      "A WOODY não pode garantir ambiente absolutamente livre de riscos. A segurança também depende do comportamento da usuária, da proteção de seus dispositivos, da confidencialidade de suas credenciais e da atuação de terceiros, como provedores de internet, lojas de aplicativos, navegadores, sistemas operacionais e serviços integrados.",
    ],
  },
  {
    heading: "4. Diretrizes da Comunidade WOODY",
    paragraphs: [
      "A WOODY existe para criar um ambiente privado, seguro e respeitoso para conexões, conversas, publicações e comunidades. Estas diretrizes indicam o comportamento esperado e os limites de uso da plataforma.",
      "4.1 Respeito e segurança — não é permitido:",
      "• Assédio, intimidação, perseguição, ameaça ou humilhação.",
      "• Discurso de ódio, discriminação, ataque a grupos protegidos ou incentivo à violência.",
      "• Linguagem abusiva, degradante, sexualmente coercitiva, invasiva ou manipuladora.",
      "• Exposição, constrangimento, vigilância, perseguição ou contato insistente após recusa ou bloqueio.",
      "4.2 Autenticidade e identidade — não é permitido:",
      "• Criar perfil falso, enganar outras usuárias ou se passar por terceiros.",
      "• Usar imagem, nome, marca, conteúdo ou identidade de outra pessoa sem autorização.",
      "• Fornecer informações falsas de forma intencional para burlar verificação, idade mínima, regras de acesso ou medidas de segurança.",
      "• Tentar vender, transferir ou compartilhar convites, contas, acessos ou benefícios.",
      "4.3 Privacidade entre usuárias — não é permitido:",
      "• Divulgar dados pessoais de terceiros sem autorização ou base legal.",
      "• Expor conversas, imagens, prints, áudios, vídeos, localização, perfis privados ou conteúdos de outras usuárias sem consentimento.",
      "• Usar informações obtidas na plataforma para perseguir, constranger, chantagear, ameaçar, discriminar ou expor outra pessoa.",
      "• Coletar dados de usuárias por scraping, automação, mineração, engenharia social ou qualquer meio não autorizado.",
      "4.4 Conteúdo proibido — não é permitido publicar, enviar, promover ou facilitar:",
      "• Conteúdo ilegal ou que viole direitos de terceiros.",
      "• Fraudes, golpes, phishing, spam, pirâmides, promessas enganosas ou manipulação comercial indevida.",
      "• Conteúdo sexual envolvendo menores de idade, exploração, coerção, chantagem ou ausência de consentimento.",
      "• Ameaças, automutilação incentivada, violência gráfica usada para choque ou intimidação, ou instruções para dano real.",
      "• Malware, tentativa de invasão, roubo de credenciais, exploração de vulnerabilidades ou burlar controles técnicos.",
      "• Informações falsas ou enganosas que possam causar dano relevante à comunidade ou a terceiros.",
      "4.5 Conteúdo adulto e consentimento",
      "Conteúdos de teor adulto, sensual ou íntimo, quando permitidos pela plataforma, devem respeitar a legislação, o consentimento das pessoas envolvidas, as regras de cada comunidade e os controles de visibilidade disponíveis. A WOODY poderá restringir, rotular, remover ou impedir conteúdos que exponham pessoas sem autorização, incentivem coerção, violem regras internas ou criem risco à segurança da comunidade.",
      "4.6 Consequências",
      "Violações podem gerar medidas proporcionais à gravidade, ao histórico da conta, ao risco gerado e ao contexto. As medidas incluem aviso, remoção de conteúdo, limitação de funcionalidades, suspensão temporária, exclusão definitiva, bloqueio de acesso e comunicação a autoridades competentes quando necessário.",
    ],
  },
  {
    heading: "5. Política de Moderação e Canal de Denúncias",
    paragraphs: [
      "A moderação existe para proteger a comunidade, reduzir abuso, preservar a proposta da plataforma e permitir respostas proporcionais a riscos e violações.",
      "5.1 Como denunciar",
      "A plataforma poderá disponibilizar botões, formulários ou canais específicos para denúncia de conteúdos, perfis, mensagens, comunidades ou comportamentos. A denúncia deve conter, quando possível, identificação do conteúdo, contexto, data aproximada e motivo da solicitação.",
      "5.2 Como as denúncias podem ser analisadas",
      "• Análise manual por equipe autorizada.",
      "• Apoio de ferramentas automatizadas para priorização, detecção de padrões ou sinais de risco.",
      "• Consulta a registros técnicos, histórico de conta, conteúdo denunciado, regras internas e legislação aplicável.",
      "• Preservação de evidências quando necessário para segurança, auditoria, defesa de direitos ou cumprimento legal.",
      "5.3 Medidas aplicáveis",
      "• Nenhuma ação, quando não houver indício suficiente de violação.",
      "• Orientação ou aviso à usuária.",
      "• Remoção, restrição ou redução de visibilidade de conteúdo.",
      "• Bloqueio de interação entre contas.",
      "• Limitação temporária de funcionalidades.",
      "• Suspensão ou exclusão de conta.",
      "• Remoção de comunidade ou intervenção em administração de comunidade.",
      "• Comunicação às autoridades competentes, quando houver obrigação legal ou risco relevante.",
      "5.4 Recursos e reavaliação",
      "Quando tecnicamente disponível e juridicamente aplicável, a usuária poderá solicitar reavaliação de determinada medida. A WOODY poderá manter medidas preventivas enquanto houver risco à segurança da plataforma, de outras usuárias ou de terceiros.",
    ],
  },
  {
    heading: "6. Segurança em interações e encontros entre usuárias",
    paragraphs: [
      "A WOODY pode facilitar conversas, descobertas, conexões e encontros. Ainda assim, a plataforma atua como intermediadora digital e não controla integralmente a identidade, intenção, conduta, histórico ou comportamento das usuárias, especialmente fora do ambiente online.",
      "• Tenha cuidado ao compartilhar telefone, endereço, local de trabalho, documentos, dados financeiros ou informações íntimas.",
      "• Desconfie de pedidos de dinheiro, urgências fabricadas, links suspeitos, promessas exageradas e pressão emocional.",
      "• Em encontros presenciais, prefira locais públicos, avise pessoa de confiança e mantenha meios próprios de deslocamento.",
      "• Use bloqueio e denúncia diante de comportamento insistente, ameaçador, abusivo, fraudulento ou invasivo.",
      "• Em situação de emergência ou risco imediato, procure autoridades competentes ou serviços locais de emergência.",
      "A WOODY não se responsabiliza por danos decorrentes de interações voluntárias entre usuárias fora da plataforma, sem prejuízo da colaboração com autoridades mediante requisição legal válida e da adoção de medidas internas quando houver violação das políticas.",
    ],
  },
  {
    heading: "7. Serviços de análise, publicidade e terceiros",
    paragraphs: [
      "A WOODY poderá utilizar serviços de terceiros para hospedagem, autenticação, armazenamento, envio de e-mails, pagamentos, suporte, segurança, análise de desempenho, mensuração, prevenção a fraude e, se aplicável, publicidade. Esses terceiros podem tratar dados conforme instruções da WOODY ou, em certas hipóteses, conforme suas próprias políticas e responsabilidades legais.",
      "• A WOODY deve limitar o compartilhamento ao necessário para a finalidade contratada.",
      "• Quando houver publicidade, mensuração ou tecnologias não essenciais, a base legal e o mecanismo de transparência devem ser avaliados de forma específica.",
      "• A usuária deve ter acesso facilitado à Política de Privacidade e à Política de Cookies, inclusive para compreender tecnologias de terceiros e preferências disponíveis.",
    ],
  },
  {
    heading: "8. Política Restritiva de Acesso",
    paragraphs: [
      "A WOODY é uma plataforma privada com proposta comunitária específica. O acesso pode ser condicionado à compatibilidade com o público permitido, à idade mínima, à autenticidade da conta, ao cumprimento das regras e à preservação da segurança da comunidade.",
      "• A definição de público existe para proteger a finalidade da plataforma e reduzir riscos de invasão, fraude, assédio e uso incompatível.",
      "• A WOODY poderá recusar, limitar, suspender ou remover contas que violem a proposta da plataforma, falsifiquem identidade, burlem verificações ou representem risco à comunidade.",
      "• Critérios de acesso devem ser aplicados com consistência, respeito à dignidade humana, transparência possível e observância da legislação aplicável.",
      "• Comunidades privadas podem adotar critérios adicionais, desde que não contrariem a lei, os Termos, as Diretrizes da Comunidade e as políticas da WOODY.",
    ],
  },
  {
    heading: "9. Disposições gerais",
    paragraphs: [
      "• Estas políticas serão regidas pela legislação brasileira.",
      "• Caso alguma disposição seja considerada inválida, as demais permanecerão aplicáveis na maior extensão permitida por lei.",
      "• A omissão ou tolerância da WOODY quanto ao descumprimento de regra não significa renúncia a direito ou autorização permanente.",
      "• A WOODY poderá atualizar as políticas para refletir mudanças legais, técnicas, operacionais, comerciais ou de segurança.",
      "• Versões anteriores poderão ser arquivadas para fins de auditoria, transparência e exercício regular de direitos.",
    ],
  },
];

export const WOODY_COOKIES_UPDATED_AT = "Versão 1.0 | Última atualização: 13 de maio de 2026";

export const WOODY_COOKIES_SECTIONS: PolicyContentSection[] = [
  {
    heading: "Política de Cookies e Tecnologias Locais",
    paragraphs: [
      "Um resumo simples de como a Woody trata dados no seu navegador neste momento - sem juridiquês excessivo, mas com honestidade. Esta política explica o uso de cookies, armazenamento local, sessão, recursos técnicos e terceiros necessários para a aplicação funcionar de forma segura e transparente.",
      "1. Escopo desta política",
      "Esta política trata especificamente de cookies e tecnologias parecidas usadas no navegador, como localStorage e sessionStorage. Ela não substitui a Política de Privacidade completa da Woody, que deve explicar, de forma mais ampla, como dados de conta, perfil, publicações, comunidades, mensagens, denúncias, pagamentos, logs e suporte são tratados.",
      "Quando falamos em “tecnologias locais”, estamos falando de recursos do próprio navegador que ajudam a manter a sessão ativa, preservar etapas de uso e permitir que a interface funcione corretamente no dispositivo da usuária.",
      "2. Cookies de rastreamento",
      "No estado atual da aplicação, a Woody não utiliza cookies próprios de rastreamento, cookies de marketing, pixels de anúncios ou cookies destinados a seguir a usuária entre sites diferentes.",
      "Também não usamos, neste desenho atual, um “cookie Woody” de analytics ou de login no sentido clássico de cookies HTTP próprios para sessão.",
      "Por isso, no cenário técnico atual, não exigimos um banner de consentimento para cookies de marketing no carregamento normal da aplicação. Se a Woody passar a usar cookies de analytics, anúncios, pixels ou tecnologias semelhantes, esta política será atualizada e, quando aplicável, serão oferecidas escolhas claras às usuárias.",
      "3. Armazenamento local da sessão",
      "Para manter a usuária autenticada depois do login, a aplicação pode guardar no navegador um token de autenticação, como um JWT, e dados mínimos de perfil necessários para a interface funcionar corretamente.",
      "Esses dados podem incluir chaves como woody_auth_token e woody_auth_user no localStorage do navegador. Isso não é um cookie, mas cumpre uma função parecida: lembrar, naquele dispositivo, que a usuária já está autenticada.",
      "A Woody deve usar essas informações apenas para viabilizar funcionalidades essenciais da aplicação, como manter a sessão ativa, identificar permissões de acesso, carregar dados básicos da conta e proteger áreas restritas.",
      "4. Dados temporários durante o onboarding",
      "Durante o onboarding, a Woody pode usar sessionStorage para guardar o progresso da usuária enquanto a aba do navegador estiver aberta.",
      "Essa prática ajuda a evitar que a usuária perca etapas no meio do fluxo, como criação de conta, validações, escolhas iniciais ou preferências temporárias.",
      "O sessionStorage costuma ser apagado quando a aba ou janela do navegador é fechada, embora o comportamento final possa variar conforme navegador, sistema operacional e configurações do dispositivo.",
      "5. API, autenticação e recursos em tempo real",
      "A aplicação se comunica com a API da Woody usando o token de autenticação da usuária, normalmente enviado no cabeçalho Authorization Bearer.",
      "Isso significa que, no desenho atual, a autenticação principal da aplicação não depende de cookies de sessão tradicionais.",
      "Para recursos em tempo real, como mensagens, avisos, notificações ou atualizações instantâneas, a Woody pode usar tecnologias como SignalR com a mesma lógica de autenticação por token.",
      "6. Pagamentos e fornecedores externos",
      "Quando houver pagamento, ele poderá ser processado por fornecedor externo especializado, como o Stripe ou outro provedor de pagamento adotado pela Woody.",
      "No desenho atual, a tendência é usar redirecionamento seguro para a página do fornecedor de pagamento, em vez de carregar diretamente campos sensíveis de pagamento dentro da página da Woody.",
      "Essa escolha reduz a quantidade de dados financeiros tratados diretamente pela Woody. Ainda assim, o fornecedor de pagamento poderá tratar dados próprios da transação conforme seus termos, políticas de privacidade e obrigações legais.",
      "7. Fontes, scripts e outros terceiros",
      "No carregamento normal da aplicação, a Woody usa as famílias Plus Jakarta Sans e Lora, ambas com licença aberta OFL, incluídas no pacote da própria aplicação e servidas pelo mesmo site.",
      "Isso significa que, no cenário atual, a aplicação não precisa fazer pedidos ao Google Fonts nem a outros CDNs de tipografia para carregar essas fontes.",
      "Se, no futuro, a Woody passar a carregar fontes, scripts, mapas, vídeos, analytics, pixels, chatbots ou outros recursos de terceiros em domínios externos, esta página será atualizada. Quando fizer sentido legal e técnico, também serão oferecidas opções de consentimento ou configuração.",
      "8. Finalidades do uso dessas tecnologias",
      "As tecnologias descritas nesta política são usadas, no cenário atual, para finalidades essenciais ou funcionais da plataforma, como:",
      "• manter a sessão da usuária ativa de forma segura;",
      "• permitir acesso a áreas autenticadas da plataforma;",
      "• preservar temporariamente etapas do onboarding;",
      "• carregar dados mínimos necessários para a interface;",
      "• apoiar recursos em tempo real, como mensagens e avisos;",
      "• reduzir fricção no uso da aplicação sem recorrer a rastreamento de marketing.",
      "9. Base legal e natureza do tratamento",
      "O uso de tecnologias essenciais para autenticação, segurança, funcionamento da conta e execução da plataforma pode estar relacionado à execução do serviço solicitado pela usuária, ao cumprimento de obrigações legais ou regulatórias e ao legítimo interesse da Woody em manter a aplicação segura e funcional, conforme o caso concreto.",
      "Quando uma tecnologia depender de consentimento específico, como cookies de marketing, pixels de publicidade ou rastreamento não essencial, a Woody deverá informar isso de forma clara e disponibilizar mecanismos adequados de escolha, quando aplicável.",
      "10. Por quanto tempo esses dados ficam no navegador",
      "Os dados guardados no localStorage podem permanecer no dispositivo até que a usuária saia da conta, limpe os dados do site no navegador, use uma função de remoção disponibilizada pela Woody ou até que a aplicação substitua esses dados por uma nova sessão.",
      "Os dados guardados no sessionStorage tendem a permanecer apenas enquanto a aba ou janela estiver aberta.",
      "Limpar dados do navegador ou sair da conta remove ou invalida dados locais daquele dispositivo, mas isso não significa, por si só, apagar a conta da usuária nem eliminar todos os dados mantidos nos servidores da Woody. Pedidos de exclusão, acesso ou correção de dados devem seguir os canais indicados na Política de Privacidade da Woody.",
      "11. Como a usuária pode controlar ou apagar esses dados",
      "A usuária pode encerrar a sessão usando a opção de sair da conta, quando disponível.",
      "Também pode limpar os dados do site nas configurações do navegador, incluindo armazenamento local, sessão e outros dados associados ao domínio da Woody.",
      "Ao limpar esses dados, algumas funcionalidades podem deixar de funcionar corretamente até que a usuária faça login novamente ou reinicie determinadas etapas.",
      "12. Segurança",
      "A Woody deve adotar medidas técnicas e organizacionais proporcionais para proteger tokens, sessões e dados tratados pela aplicação, incluindo controles de autenticação, autorização, expiração de sessão, validações no backend e práticas de desenvolvimento seguro.",
      "A Woody cuida da segurança da plataforma com responsabilidade, mas proteção também é um cuidado compartilhado. Nenhum mecanismo técnico é absoluto. Por isso, recomendamos que cada usuária proteja seu dispositivo, não compartilhe conta ou senha, mantenha o navegador atualizado e saia da conta ao usar aparelhos compartilhados.",
      "13. O que a Woody não faz no cenário atual",
      "No carregamento normal da aplicação, conforme o desenho técnico atual, a Woody não usa cookies de marketing, pixels de anúncios ou rastreadores destinados a acompanhar a usuária entre diferentes sites.",
      "Também não vende dados pessoais de usuárias para anunciantes.",
      "Se algum desses pontos mudar, a política será atualizada antes ou junto da mudança relevante, com comunicação compatível com o impacto da alteração.",
      "14. Direitos das usuárias",
      "As usuárias podem exercer direitos previstos na legislação aplicável de proteção de dados, incluindo confirmação da existência de tratamento, acesso, correção, eliminação, informação sobre compartilhamento, revisão de decisões automatizadas quando aplicável e outros direitos previstos em lei.",
      "Pedidos relacionados a dados pessoais devem ser enviados pelos canais oficiais indicados pela Woody na Política de Privacidade ou em seus meios de contato institucionais.",
      "Esta política explica tecnologias locais do navegador; pedidos sobre dados de conta, publicações, comunidades, mensagens, pagamentos ou denúncias devem ser tratados pela Política de Privacidade completa.",
      "15. Alterações nesta política",
      "A Woody pode atualizar esta política para refletir mudanças técnicas, legais, operacionais ou de produto.",
      "Se forem adicionadas tecnologias não essenciais, como analytics, anúncios, pixels ou fornecedores de rastreamento, a Woody deverá atualizar as informações desta página e, quando necessário, disponibilizar escolhas adequadas às usuárias.",
      "A versão mais recente desta política deve ficar disponível em local acessível dentro da aplicação ou do site da Woody.",
      "16. Contato",
      "Para dúvidas sobre esta política, privacidade ou tratamento de dados pessoais, a usuária pode entrar em contato com a Woody pelo canal oficial informado na aplicação.",
      "Contato para privacidade: [inserir e-mail oficial da Woody].",
      "Controladora: [inserir razão social ou nome da responsável pela Woody, quando definido].",
      "Nota de uso: este documento foi estruturado para informar as usuárias com clareza e reduzir riscos de inconsistência na comunicação da Woody. Antes de publicação definitiva, recomenda-se revisar os campos pendentes e alinhar esta política com a Política de Privacidade, Termos de Uso e implementação técnica real da aplicação.",
    ],
  },
];
